### ISSUE TITLE
Client secret exposure risk

### ISSUE THREAD

**Issue by dirname** [casdoor/casdoor-wechat-miniprogram-example#1]
Refer to [Write WeChat MiniProgram code](https://casdoor.org/docs/integration/wechat_miniprogram#step3-write-wechat-miniprogram-code).

```
// login in mini program
          ....
          data: {
            "tag":"wechat_miniprogram", //required
            "client_id":"6825f4f0af45554c8952",
            "client_secret": "2d0f463...",
            "code": res.code,
            "username": this.data.userInfo.nickName, //update user profile, when you login.
            "avatar": this.data.userInfo.avatarUrl,
          },
          ....
````

`"client_secret": "2d0f463...",`   is the client secret of the casdoor application, which may be exposed through http capture, etc.

**Comment by hsluoyz** [comment]
Hi @Steve0x2a what do you think?

**Comment by hsluoyz** [comment]
@Resulte @ziliangyu

**Comment by Zerek-Cheng** [comment]
You can consider sending it to the server and exchanging tokens at the server

**Comment by hsluoyz** [comment]
@Zerek-Cheng @dirname what's the standard way to handle this from Tencent?

**Comment by dirname** [comment]
> You can consider sending it to the server and exchanging tokens at the server

This issue is an example in a document. Due to security reasons, I think the risk needs to be noted in the document or abandon this example directly and handle it on the server side.

**Comment by hsluoyz** [comment]
@dirname can you point me to the WeChat official docs saying about this?

**Comment by dirname** [comment]
Here is the paragraph about obtaining a [Client Secret](https://www.rfc-editor.org/rfc/rfc6819#section-4.1.1) and its relative consequences(RFC6819).

**Comment by hsluoyz** [comment]
@dirname fixed at: https://github.com/casdoor/casdoor-website/pull/313
